### ISSUE TITLE
下载新代码编译不过

### ISSUE THREAD

**Issue by xbpengbenden** [hrscy/TodayNews#13]
![image](https://user-images.githubusercontent.com/5183330/27331152-ef00a312-55ee-11e7-999b-bcf4b3058b4b.png)
![image](https://user-images.githubusercontent.com/5183330/27331175-00c7c206-55ef-11e7-92b8-286158521990.png)

**Comment by hrscy** [comment]
现在可以了，你重新下载试试

**Comment by imlcl** [comment]
依，真的可以通过野

**Comment by imlcl** [comment]
![image](https://user-images.githubusercontent.com/827020/27375973-55523b08-56a3-11e7-8105-735440d32553.png)
运行时提示这个，不知是啥原因？

**Comment by xbpengbenden** [comment]
是的，可以了，谢谢

**Comment by hrscy** [comment]
@imlcl https://github.com/Alamofire/Alamofire/issues/101 看一下这个
