### ISSUE TITLE
编译找不到 AllConcernsCell这个类

### ISSUE THREAD

**Issue by powercen** [hrscy/TodayNews#14]
TodayNews/TodayNews/Classes/Mine/Controller/MyConcernController.swift:23:142: Use of unresolved identifier 'AllConcernsCell'

编译找不到 AllConcernsCell这个类，求解

**Comment by powercen** [comment]
是不是把这个AllConcernsCell类忘记上传了

**Comment by hrscy** [comment]
你可以去文件夹里找一下 Mine/View/AllConcernsCell.swift，应该有这个文件的
