### ISSUE TITLE
兼容3.0

### ISSUE THREAD

**Issue by Tuikai** [hrscy/TodayNews#15]
希望作者能抽时间完成3.0适配,另外现在的版本下载下来无法运行,环境-->Xcode8,加油,向你学习

**Comment by hrscy** [comment]
我现在使用 xcode 版本是 8.3.2，你可以把 xcode 升级到最新版本不会出现编译不过的问题了。

**Comment by Tuikai** [comment]
`fileprivate lazy var pageView: HomePageView = {
        let pageView = HomePageView()
        return pageView
    }()` homeViewController第48行,报错

**Comment by hrscy** [comment]
请下载最新代码运行一下看有没有问题。

**Comment by AllocAndInit** [comment]
项目下载下来以后有几个文件找不到，目前Xcode 的版本是 8.3.3
![wx20170707-151058](https://user-images.githubusercontent.com/19301846/27946960-99c85472-6326-11e7-953d-129cd541f843.png)

**Comment by hrscy** [comment]
@AllocAndInit 这些文件已经删除，请下载最新代码查看
