### ISSUE TITLE
Value of type 'NSData' has no member 'getCRC32'

### ISSUE THREAD

**Issue by MycroftWong** [hrscy/TodayNews#17]
![image](https://user-images.githubusercontent.com/12746309/29071837-d99302ea-7c77-11e7-876d-45b1ecf10f6d.png)
git下来编译是这样，我刚学，这个方法是被抛弃了还是什么原因，编译报错，没有这个方法

**Comment by hrscy** [comment]
看一下这个路径 TodayNews/Classes/Main/Category/NSData+CRC32.h 有没有这个文件，
还有这个桥接文件 /TodayNews/Classes/Main/Category/TodayNews-Bridging-Header.h
![image](https://user-images.githubusercontent.com/16634163/29079365-9aeadc26-7c8f-11e7-8bc7-4614e7ab1b2d.png)
在 build phases 里添加 libz.tbd
试一下

**Comment by MycroftWong** [comment]
@hrscy 两个文件都有，添加了libz.tbd没有什么变化，尝试过重新打开项目，clean也不行，请问还可能是什么问题

**Comment by hrscy** [comment]
我刚刚下载了最新的代码编译了一下，没有问题，你试试下载最新的代码看看能不能编译通过

**Comment by MycroftWong** [comment]
@hrscy ok 没问题了，编译通过
