### ISSUE TITLE
Use of unresolved identifier 'RefreshHeder'

### ISSUE THREAD

**Issue by rocwangv** [hrscy/TodayNews#18]
您好，下载代码后出现这个异常：
`
Use of unresolved identifier 'RefreshHeder'
`
<img width="237" alt="qq20170817-164713 2x" src="https://user-images.githubusercontent.com/15099302/29403727-c4a206a6-836b-11e7-9734-737df2a16cd3.png">

**Comment by hrscy** [comment]
看一下这个路径 Classes/Main/View/RefreshHeder.swift存不存在，把这个文件拖到工程里就可以了。

**Comment by hrscy** [comment]
[RefreshHeder.swift](https://github.com/hrscy/TodayNews/blob/master/TodayNews/Classes/Main/View/RefreshHeder.swift)
这个文件是有的。

**Comment by rocwangv** [comment]
感谢大佬。是因为`view`这个目录不在工程里面，拖进去就好了。
