### ISSUE TITLE
ym_registerCell缺少这个方法

### ISSUE THREAD

**Issue by xiao4930772** [hrscy/TodayNews#20]
运行Demo  没有这个方法(ym_registerCell),还有ym_dequeueReusableCell

**Comment by hrscy** [comment]
看一下这个文件 [UITableView+Extension.swift](https://github.com/hrscy/TodayNews/blob/master/TodayNews/Classes/Main/Category/UITableView%2BExtension.swift)

**Comment by xiao4930772** [comment]
git上有这个分类，但是下载的zip文件 解压后 确实是没有那个分类

**Comment by hrscy** [comment]
你检查一下，看看所在的文件夹有没有，可能有的时候文件没有复制到项目里去，找到这个文件，然后拖到项目里就可以了

**Comment by xiao4930772** [comment]
文件是没有的

**Comment by hrscy** [comment]
现在再看呢？我又提交了一下
