### ISSUE TITLE
项目下载下来后还是很多报错

### ISSUE THREAD

**Issue by cuixinle** [hrscy/TodayNews#21]
ym_registerCell ，ym_dequeueReusableCell这几个都报错

**Comment by hrscy** [comment]
现在在看呢？我又提交了一下，这个文件是有的
[UITableView+Extension](https://github.com/hrscy/TodayNews/blob/master/TodayNews/Classes/Main/Category/UITableView%2BExtension.swift)

**Comment by cuixinle** [comment]
OK

**Comment by cuixinle** [comment]
可以加下你的QQ沟通吗？？

**Comment by cuixinle** [comment]
我这边更新运行 还是很多报错，提示计算文字高度的，attributes: [.font 这里 提示font错误。

**Comment by hrscy** [comment]
我这边是使用 xcode 9 编译通过的，并且 swift 版本选择的是 swift 4.0，你需要升级一下的 xcode，上面的属性在 xcode 9 中发生了改变。

**Comment by cuixinle** [comment]
OK

**Comment by cuixinle** [comment]
发现几个小bug。
1、has_video 为nil时闪退，见下图
![snip20171005_1](https://user-images.githubusercontent.com/13199625/31214580-640174dc-a9de-11e7-99d6-48895416ddaa.png)
2、app中播放视频不能全屏播放，其次在上下滑动时，会改变屏幕亮度和声音大小
3、视频播放时，多页面切换可以同时播放多个视频，已被切换过去的页面视频仍在继续播放。

**Comment by hrscy** [comment]
感谢反馈，后面有时间我会修复。
