### ISSUE TITLE
项目下载下来有好多报错。是打开方式不对没？

### ISSUE THREAD

**Issue by Manlinup** [hrscy/TodayNews#22]
先是“TodayNews" requires a provisioning profile.
然后各种import的库找不到。

**Comment by hrscy** [comment]
[issues23](https://github.com/hrscy/TodayNews/issues/23)

**Comment by hrscy** [comment]
provisioning profile 的问题，你可以把 team 改成 none。
![image](https://user-images.githubusercontent.com/16634163/31998827-c34e1f3a-b956-11e7-94f6-0f0ffa9a9c7a.png)

**Comment by hrscy** [comment]
最新的代码我已上传，编译没有问题。
