### ISSUE TITLE
XCode 9+Swift 4 compile fail，pod依赖没更新

### ISSUE THREAD

**Issue by canchew** [hrscy/TodayNews#23]
修改了很多项pod依赖才编译成功，感觉作者忘记提交最新的pod文件了

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "TodayNews" do
    pod 'SnapKit', '~> 4.0.0'           # 布局框架 https://github.com/SnapKit/SnapKit，同 Masonry
    pod 'Kingfisher', '~> 4.0.0'        # 缓存图片 https://github.com/onevcat/Kingfisher，同 SDWebImage
    pod 'Alamofire', '~> 4.5.0'         # 数据请求 https://github.com/Alamofire/Alamofire，同 AFNetworking
    pod 'SwiftyJSON', '~> 3.1.4'        # json 解析 https://github.com/SwiftyJSON/SwiftyJSON
    pod 'IBAnimatable'                  # 设计原型，自定义 UI，交互，导航，转场和动画 https://github.com/IBAnimatable/IBAnimatable
    pod 'RxSwift', '~> 4.0'             # 响应式编程框架 https://github.com/ReactiveX/RxSwift
    pod 'RxCocoa', '~> 4.0'             # 响应式编程框架 https://github.com/ReactiveX/RxSwift
    pod 'SVProgressHUD', '~> 2.1.2'     # 提示功能 https://github.com/SVProgressHUD/SVProgressHUD
    pod 'MJRefresh'                     # 上拉和下拉刷新框架 https://github.com/CoderMJLee/MJRefresh
    pod 'BMPlayer'                      # 视频播放框架 https://github.com/BrikerMan/BMPlayer
    pod 'LeanCloud'                     # 云存储功能，可作为后台，模拟登录 https://leancloud.cn/docs/sdk_down.html
    pod 'SwiftTheme'                    # 主题替换方案 https://github.com/jiecao-fm/SwiftTheme
    pod 'HandyJSON', '4.0.0-beta.1'
    
end

我改成上面这样编译成功了，Mac OS 10.12.6

**Comment by hrscy** [comment]
非常感谢，我已经把 pod 库更新了。
