### ISSUE TITLE
Xcode8 报错怎么处理？

### ISSUE THREAD

**Issue by iHTCboy** [hrscy/TodayNews#3]
SwiftyJSON will not be code signed because its settings don't specify a development team.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by FeedHedgehog** [comment]
现在项目只支持到swift2.3，还没有升级3.0

**Comment by hrscy** [comment]
年后会更新
