### ISSUE TITLE
请求首页列表接口的api会有返回重复数据的情况吗？

### ISSUE THREAD

**Issue by LoveqLRC** [hrscy/TodayNews#30]
rt 例如这种接口[https://is.snssdk.com/api/news/feed/v64/?device_id=8800803362&category=news_hot](url)，我在浏览器刷了几次没看到有重复的数据，我想问一下：实际上会不会存在返回重复数据的情况(也就是说上一次请求已经返回过这条新闻了，这次请求包含了上一次请求的新闻的情况)。

**Comment by hrscy** [comment]
如果重复请求的数据的话，可能会出现重复数据。
目前加载更多还是相当于重复请求接口，我现在还没做处理。

**Comment by LoveqLRC** [comment]
我用fiddler看了一下，居然没发现有分页请求接口~~
