### ISSUE TITLE
MKdocs的配置文件格式已经改了

### ISSUE THREAD

**Issue by LinMaris** [hrscy/TodayNews#35]
MKdocs的配置文件格式已经改了 现在应该是这个
 - 索引: index.md

**Comment by hrscy** [comment]
请进入这个目录 [news-docs](https://github.com/hrscy/TodayNews/tree/master/news-docs)
![image](https://user-images.githubusercontent.com/16634163/36543771-b9fc8ce6-181f-11e8-9a99-b499dd7df9f6.png)
在浏览器中输入 127.0.0.1:8000，会出现下面的界面：
![image](https://user-images.githubusercontent.com/16634163/36543797-ce880e88-181f-11e8-8e29-ec3b01f8734e.png)
