### ISSUE TITLE
No such module 'IBAnimatable'

### ISSUE THREAD

**Issue by developerworks** [hrscy/TodayNews#38]
XCode Version 9.2 (9C40b)
➜  News git:(master) ✗ pod --version
1.4.0

![image](https://user-images.githubusercontent.com/725190/37754736-c18dab6a-2ddd-11e8-88d3-281424016dd5.png)

**Comment by developerworks** [comment]
![image](https://user-images.githubusercontent.com/725190/37755531-cf3ec69c-2de0-11e8-8400-891568e994c0.png)

**Framework Search Paths** 里面是有的.

**Comment by hrscy** [comment]
您好，请到这里私信我一下 [简书主页](https://www.jianshu.com/u/c0a496a1c168)。
