### ISSUE TITLE
运行崩溃

### ISSUE THREAD

**Issue by HZChenCheng** [hrscy/TodayNews#39]
今天升级的最新的Xcode和iOS系统，运行会奔溃

**Comment by hrscy** [comment]
最新代码已经上传，Xcode 9.3 运行成功。
问题原因参考[Xcode9.3 Swift4.1 crash 解决方案](https://github.com/alibaba/HandyJSON/issues/239)。请按照上面的方法改一下代码然后再编译运行试试。😉
