### ISSUE TITLE
在当前类里extension的方法（//Mark: - XXXXXXXXXX）是手写的还是插件载入的

### ISSUE THREAD

**Issue by xusheng927** [hrscy/TodayNews#4]
刚开始接触Xcode，求快速实现的方法。快捷键或者插件都行

**Comment by hrscy** [comment]
手写的，你可以设置快捷方式，提前设置好 //Mark: - XXXXXXXXXX 然后拖动到属性面板 的 {} 选项里面。

**Comment by hrscy** [comment]
@xusheng927  目前正在适配 Swift 3.1 可以移步 [TodayNews-Swift](https://github.com/hrscy/TodayNews/tree/master/TodayNews-Swift)
