### ISSUE TITLE
Handy json报错

### ISSUE THREAD

**Issue by narakai** [hrscy/TodayNews#40]
var numberOfFields: Int {
        return Int(pointer.pointee.numberOfFields)
    }

Thread 1: EXC_BAD_ACCESS (code=1, address=0x2

**Comment by hrscy** [comment]
最新代码已经上传，Xcode 9.3 运行成功。
问题原因参考[Xcode9.3 Swift4.1 crash 解决方案](https://github.com/alibaba/HandyJSON/issues/239)。请按照上面的方法改一下代码然后再编译运行试试。😉

**Comment by narakai** [comment]
已修复，给力！
