### ISSUE TITLE
xcode 8.2 编译一堆error，能修复一下吗？

### ISSUE THREAD

**Issue by moozhd** [hrscy/TodayNews#9]
xcode 8.2 编译一堆error，能修复一下吗？
大神啊，有个地方想请教一下，我的企鹅号（923988022）能加一下吗，指导一下……

**Comment by AndyDufresneTheShadow** [comment]
xcode 8.2 编译一堆error，能修复一下吗？
大神啊，有个地方想请教一下，我的企鹅号（923988022）能加一下吗，指导一下……

**Comment by hrscy** [comment]
目前正在适配 Swift 3.1 可以移步 [TodayNews-Swift](https://github.com/hrscy/TodayNews/tree/master/TodayNews-Swift)
